package com.yancy.yharness.hooks;

public enum HookType {
    SESSION_START,
    CONTEXT_ASSEMBLING,
    MEMORY_RETRIEVED,
    BEFORE_MODEL_CALL,
    AFTER_MODEL_CALL,
    BEFORE_TOOL_CALL,
    AFTER_TOOL_CALL,
    BEFORE_SESSION_SUMMARIZE,
    CONVERSATION_UPDATED,
    STORY_UPDATED,
    SESSION_END,
    ERROR
}